
export const ErrorStatus = {
    INVALID_INPUT_DATA: "INVALID_INPUT_DATA",
    NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
    NOT_FOUND: "NOT_FOUND",
    ALREADY_DONE: "ALREADY_DONE",
    ALREADY_EXIST: "ALREADY_EXIST",
    NOT_ENOUGH_PERMISSIONS: "NOT_ENOUGH_PERMISSIONS",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    UNKNOWN_ERROR: "UNKNOWN_ERROR"
}

export const ERole = {
    SCOUT: "SCOUT",
    PLAYER: "PLAYER",
}

export const Gender = {
    MALE: "MALE",
    FEMALE: "FEMALE",
    OTHER:"OTHER",
    UNKNOWN:"UNKNOWN"
}


export const VideoRequestStatus = {
    PENDING: "PENDING",
    ACCEPTED: "ACCEPTED",
    REJECTED: "REJECTED"
}

export const ENotificationType = {
    VIDEO_REJECTION: "VIDEO_REJECTION",
    VIDEO_ACCEPTANCE: "VIDEO_ACCEPTANCE"
}

export const VRejectionReason = {
    QUALITY: "QUALITY",
    VIOLATION_OF_POLICY: "VIOLATION_OF_POLICY",
    DURATION: "DURATION"
  } 
    